name: Shinoo

on:
   workflow_dispatch

jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Find PRs merged after specific PR
      id: list-prs
      run: |
        # Find the PR with the specific title
        SPECIFIC_PR_TITLE="Merge release branch into main"  # replace with your specific PR title
        SPECIFIC_PR=$(gh pr list --state merged --search "$SPECIFIC_PR_TITLE in:title" --json number,title,mergeCommit)
        
        if [ -z "$SPECIFIC_PR" ]; then
          echo "No PR found with title $SPECIFIC_PR_TITLE"
          exit 1
        fi
        
        SPECIFIC_PR_MERGE_COMMIT_SHA=$(echo $SPECIFIC_PR | jq -r '.[0].mergeCommitSha')

        # List PRs merged after the specific PR
        PRS=$(gh pr list --state merged --search "merged:>$SPECIFIC_PR_MERGE_COMMIT_SHA" --json number,title,url)
        echo "::set-output name=prs::$PRS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  create-file-and-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create new branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b new-branch

    - name: Create a new file
      run: |
        echo "::set-output name=prs::$PRS" > newfile.txt
        git add newfile.txt
        git commit -m "Add newfile.txt"

    - name: Push new branch
      run: |
        git push --set-upstream origin new-branch

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: new-branch
        title: "Add newfile.txt"
        body: "This PR adds newfile.txt to the repository."
