name: Shinoo

on:
   workflow_dispatch:
      inputs:
         board:
           description: 'Choose an option'
           required: true
           type: choice
           options:
             - APP
             - SN
             - VLC
             - PLAT
             - GRF
jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Find PRs merged after specific PR
      id: list-prs
      run: |  
        SPECIFIC_PR_MERGE_COMMIT_SHA=$(gh pr list --state merged --search "Merge release branch into main in:title" --json mergedAt | jq -r '.[0].mergedAt')
        MERGE_COMMIT_ISO_DATE="${SPECIFIC_PR_MERGE_COMMIT_SHA}Z"
        PRS=$(gh pr list --state merged --search "created:>$MERGE_COMMIT_ISO_DATE" --json title)
        echo "| Ticket                       | Tester   | Status 🥑 🌶 " >> table.md
        echo "|------------------------------|----------| ------------" >> table.md
        for FILE in $PRS; do
           title=$(jq -r '.[0].title' <<< "$FILE")
           echo "| $title                    |           |             " >> table.md
        done
        TABLE_CONTENT=$(cat table.md)
        TABLE_CONTENT_ESCAPED=$(echo "$TABLE_CONTENT" | sed ':a;N;$!ba;s/\n/\\n/g')
        curl -X POST \
            -H "Content-Type: application/json" \
            -u $JIRA_USERNAME:$JIRA_API_TOKEN \
            --data '{
              "fields": {
                "project": {
                  "id": "PLAT"
                },
                "summary": "Test issue from GitHub Action",
                "description": "Creating an issue via GitHub Actions",
                "issuetype": {
                  "name": "Task"
                }
              }
            }' \
            $JIRA_BASE_URL/rest/api/2/issue
          project: 'PLAT'
          description: $TABLE_CONTENT_ESCAPED
          issuetype: 'Task'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          
